language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- python setup.py install
- pip install coverage
- pip install coveralls
script:
- coverage run --source=random_phone setup.py test
after_success:
- coveralls